survive_disambiguator.c: handle_lightcap: early out with false when _le->length == 0
collabora/libsurvive pull request #316
Opened 2024-10-21 11:53 UTC by throni3git

This broke my program flow sometimes. See #311

2026-07-13 15:10 UTC, bl4ckb0ne requested changes

2026-07-13 15:10 UTC, bl4ckb0ne commented on src/survive_disambiguator.c
> +	// "assert(_le->length > 0);" sometimes breaks the whole program, so instead just return success = false and go on
The comment isnt relevant anymore, the assert has been removed.

2026-08-03 08:32 UTC, throni3git commented on src/survive_disambiguator.c
> +	// "assert(_le->length > 0);" sometimes breaks the whole program, so instead just return success = false and go on
that is true. i finally removed it :)

2026-08-10 18:51 UTC, bl4ckb0ne approved these changes
Thanks!

2026-08-10 18:52 UTC, merged